# Generated by Django 4.2.3 on 2023-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherDataProcessing', '0002_weatherdata_visibility_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='heat_index',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='rainfall_index',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='visibility_index',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_index',
            field=models.CharField(default='', max_length=100),
        ),
    ]
